# -*- coding:GBK-*-
#========================================================================
#   FileName: cc_calldetail.py
#     Author: linh
#      Email: linh@ecallcen.com
#   HomePage: 中兴的cc_calldetail表对应的类
# LastChange: 2012-08-18 20:08:03
#========================================================================
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import MetaData, Table, Column,\
                        Integer, String, create_engine,DateTime
Base = declarative_base()
class cc_calldetail(Base):
    __tablename__ = 'cc_calldetail'
    connectionid=Column(String(40),primary_key=True)
    vcid=Column(Integer)
    calltype=Column(Integer)
    strcallday=Column(String(10))
    callstarttime=Column(DateTime)
    callendtime=Column(DateTime)
    callresult=Column(Integer)
    callingnumber=Column(String(32))
    oricallednumber=Column(String(32))
    callednumber=Column(String(32))
    servicekey=Column(Integer)
    ringingstarttime=Column(DateTime)
    answertime=Column(DateTime)
    customtype=Column(Integer)
    areacode=Column(String(32))
    nettype=Column(Integer)
    outcallfailcode=Column(Integer)
    fakecalling=Column(String(32))
    updatetime=Column(DateTime)
    firstqueueskill=Column(Integer)
    firstqueuesstarttime=Column(DateTime)
    firstqueueendtime=Column(DateTime)
    firstqueueresult=Column(Integer)
    firstagentid=Column(String(10))
    firstagentphone=Column(String(32))
    firstringingstarttime=Column(DateTime)
    firstagentanswertime=Column(DateTime)
    firstagentabandoned=Column(Integer)
    firstagentendtime=Column(DateTime)
    endqueueskill=Column(Integer)
    endqueuesstarttime=Column(DateTime)
    endqueueendtime=Column(DateTime)
    endqueueresult=Column(Integer)
    endagentid=Column(String(10))
    endagentphone=Column(String(32))
    endringingstarttime=Column(DateTime)
    endagentanswertime=Column(DateTime)
    endagentabandoned=Column(Integer)
    endagentendtime=Column(DateTime)
    iscustomrelease=Column(Integer)
    totalqueuecount=Column(Integer)
    totalqueuetime=Column(Integer)
    totalholdcount=Column(Integer)
    totalholdtime=Column(Integer)
    totalconsultivrcount=Column(Integer)
    totalconsultivrtime=Column(Integer)
    totalconsultcount1=Column(Integer)
    totalconsulttime1=Column(Integer)
    totalconsultivrcount2=Column(Integer)
    totalconsulttime2=Column(Integer)
    totalivrtransfercount=Column(Integer)
    totalagenttransfercount=Column(Integer)
    totaltransferoutcount=Column(Integer)
    totalparkcount=Column(Integer)
    totalparktime=Column(Integer)
    abnormalcall=Column(Integer)
    consultskillnum=Column(Integer)
    consultskilltime=Column(Integer)
    lastagentid=Column(Integer)
    oriconnectionid=Column(Integer)
    callingc3fdevice=Column(Integer)
    calllocalid=Column(Integer)
    endqueuevc=Column(Integer)
    isconnect=Column(Integer)
    convcid=Column(Integer)
    conagentid=Column(String(10))
    conskill=Column(Integer)
    conlevel=Column(Integer)
    conagentanswertime=Column(DateTime)
    firstreportworkflag=Column(Integer)
    firstreportworkend=Column(DateTime)
    endreportworkflag=Column(Integer)
    endreportworkend=Column(DateTime)
    firstresultcode=Column(Integer)
    endresultcode=Column(Integer)
    usrlocal=Column(String(20))
    iwconnectionid=Column(String(20))
